### ISSUE TITLE
Can't build web module

### ISSUE THREAD

**Issue by SekibOmazic** [benawad/monorepo-boilerplate#35]
Hi,

I've just tried to build the project and `yarn build:server` works just fine but `yarn build:web` fails with:

```
⇒  yarn build:web
yarn run v1.12.3
$ lerna run build --scope={@codeponder/common,@codeponder/web}
lerna notice cli v3.6.0
lerna info filter [ '@codeponder/common', '@codeponder/web' ]
lerna info Executing command in 2 packages: "yarn run build"
lerna info run Ran npm script 'build' in '@codeponder/common' in 3.7s:
$ tsc
lerna ERR! yarn run build exited 1 in '@codeponder/web'
lerna ERR! yarn run build stdout:
$ next build
[12:18:54] Compiling client
[12:18:54] Compiling server
> Using external babel configuration
> Location: "/Users/sekibomazic/Documents/projects/sekib/monorepo/packages/web/.babelrc"
[12:19:00] Compiled server in 6s
[12:19:08] Compiled client in 15s
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
> Failed to build
{ Error: (client) ./pages/home.tsx
Module not found: Error: Can't resolve '@codeponder/ui' in '/Users/sekibomazic/Documents/projects/sekib/monorepo/packages/web/pages'
 @ ./pages/home.tsx 20:0-40 36:33-39
```
For some reason `@codeponder/ui` can't be found from `home.tsx` in the web module.

Any hints on how to solve this?

**Comment by benawad** [comment]
We need to build `@codeponder/ui` too. I added the fix to the root `package.json` https://github.com/benawad/monorepo-boilerplate/blob/master/package.json

**Comment by SekibOmazic** [comment]
That didn't work for me. Still getting same error. I've tries with different node versions (11 and 8) but no luck.

**Comment by SekibOmazic** [comment]
Btw. in Codeponder project you also have just:
```
"scripts": {
    "build:server": "lerna run build --scope={@codeponder/common,@codeponder/server}",
    "build:web": "lerna run build --scope={@codeponder/common,@codeponder/web}"
  },
```

**Comment by audiBookning** [comment]
Did you git pull? The latest version should contain the build for the ui.
You can also do it directly by going to the packages/ui folder and 'yarn build'.

**Comment by SekibOmazic** [comment]
I even cloned the repo again, but still no luck. Building form the terminal fails as well. 
Running `yarn build:web` from the root will build `ui` module successfully. But `web` module still fails. I've even tried from another macBook also without luck. 
Pretty strange.

**Comment by audiBookning** [comment]
Try this:
- start the server: cd to packages/server and 'yarn start'
- run gql-gen: cd to packages/web and 'yarn generate'
- and finally 'yarn dev'

**Comment by SekibOmazic** [comment]
Well it all works until I try to visit: `http://localhost:3000/home`. Then I get:
```
./pages/home.tsx
Module not found: Can't resolve '@codeponder/ui' in '/Users/sekibomazic/Documents/projects/sekib/monorepo-boilerplate/packages/web/pages'
```

**Comment by audiBookning** [comment]
just tried from a clean folder and i can confirm that i am having the same error as you.

**Comment by benawad** [comment]
I'll take a look at this in a couple hours

**Comment by benawad** [comment]
just pushed a commit that should fix this problem

**Comment by SekibOmazic** [comment]
@benawad Thanks, that fixed the issue.
